# Numpy Intro 

In [2]:
import numpy as np

In [2]:
np.random.seed(1337)

## Basics of Matrices 

In [3]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [7]:
y = np.array([[1, 4, 3], 
              [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [9]:
x.shape

(3,)

In [10]:
y.shape

(2, 3)

In [14]:
z = np.array([[1, 4, 3]])   # What's the difference? 

In [12]:
z.shape

(1, 3)

In [24]:
z = np.arange(1, 2000, 1)  # start, end, step
z[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
z.shape

(1999,)

In [26]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
np.arange(0.5, 10, 1).shape

(10,)

In [9]:
np.arange(0.5, 10, 1).reshape(5, 2).shape

(5, 2)

In [10]:
np.arange(0.5, 10, 1).reshape(5, 3).shape  # !! 

ValueError: cannot reshape array of size 10 into shape (5,3)

In [30]:
# Evenly spaced but we don't know the step 
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [34]:
print(x)
print(x[1]) 
print(x[1:])

[1 4 3]
4
[4 3]


In [35]:
print(y)
y[0, 1]   # this is extra in numpy 

[[1 4 3]
 [9 2 7]]


4

In [37]:
y[:, 1]

array([4, 2])

In [39]:
y[:, [1, 2]]

array([[4, 3],
       [2, 7]])

## Matrix Operations 

In [40]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [12]:
a.shape

(6,)

In [45]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [47]:
a[:3] = 1   # Assign to multiple locations 
a

array([1, 1, 1, 7, 5, 6])

In [48]:
a[1:4] = [9, 8, 7]
a

array([1, 9, 8, 7, 5, 6])

In [14]:
# This is most useful 
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 1] = 4
b

array([[1., 2.],
       [0., 4.]])

In [15]:
b.shape

(2, 2)

## Array Operations 

In [60]:
print(b)

[[1. 2.]
 [0. 4.]]


In [51]:
b + 2

array([[3., 4.],
       [2., 6.]])

In [64]:
2 * b

array([[2., 4.],
       [0., 8.]])

In [65]:
b ** 2

array([[ 1.,  4.],
       [ 0., 16.]])

In [52]:
sum(b)

array([1., 6.])

In [61]:
b.sum()

7.0

In [62]:
b.sum(axis=0)

array([1., 6.])

In [63]:
b.sum(axis=1)

array([3., 4.])

In [66]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [67]:
print(b) 
print(d)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [70]:
b + d 

array([[ 4,  6],
       [ 8, 10]])

In [71]:
b * d     # what operation is this? 

array([[ 3,  8],
       [15, 24]])

In [72]:
b.dot(d)  # and this? 

array([[13, 16],
       [29, 36]])

In [73]:
b ** d 

array([[   1,   16],
       [ 243, 4096]])

In [74]:
b.T

array([[1, 3],
       [2, 4]])

In [79]:
# Numpy has "broadcasting" or "mapping" functions 
print(np.sqrt(36))

# works on both scalars and arrays 
x = [1, 4, 9, 16]
np.sqrt(x)

6.0


array([1., 2., 3., 4.])

In [80]:
# Checking conditions 
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [81]:
x > 3 

array([False, False,  True,  True,  True, False])

In [82]:
x > y 

array([ True, False,  True,  True,  True, False])

## Measures of Vector Lengths

The **norm** of a vector defines a measure of it's length. It depends on what measure you're interested in. Let's first see those measures very briefly. 

### Euclidean Distance 

Euclidean distance is what you would be familiar with from your early education. (Remember Pythogoras.)


Distance between two points $(x_1, y_1)$ and $x_2, y_2)$ is given as $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$. 

Let's view the notebook for details about this. 