# Linear Algebra Basics

## Why Study Linear Algebra? 

Think of Linear Algebra as basic operatons on vectors and matrices. 

You've seen how we can represent groups of numbers in vectors and matrices. This makes them easier to manage. But once we do that, we need to be able to decide what *add*, *subtract*, *multiply* etc. mean on these "numbers". 

So, we learn Linear Algebra so that we can do basic maths on these "numbers". We'll see examples of parallels here in a while. 

## Vectors 

A **vector** in ${\mathbb{R}}^n$ is an $n$-tuple. That means a shape of  `(n,)`. They can be *horizontal* and are called **row vectors** or vertical in which case they are called **column vectors** (the default).

We created and looked at basic vectors in the numpy intro. 

## Vector Norm

The **norm** of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). So, let's take a look at some distance formulae first. 

### Euclidean Distance 

Euclidean distance is what you are already familiar with. The Euclidean distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is given as: 

$$ 
\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$

Visually, this would look like this: 

If we take any vector and take it's x- and y-coordinates as its components, we can redefine the above like so:

This length is then called the *L-2 Norm* of the vector -- the stuff you know as the magnitude. The specific formula then is: 

$$\Vert v \Vert_{2} = \sqrt{\sum_i v_i^2}$$

where $v_i$ are the elements of the vector $v$.

### Manhattan Distance 

What happens if we don't square the values? It doesn't make sense in the pythogarean sense of the value but sometimes, it is quite useful.

Let's first see what the Manhattan distance between two points is. 

The Manhattan distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is given as: 

$$ 
(x_2 - x_1) + (y_2 - y_1)
$$

So, basically just adding up the components. Visualy, this looks like this: 

And the formula is simple too: 

$$\Vert v \Vert_{1} = \sum_i |v_i|$$

Let's try this out! 

## Numpy Vectors Revisited

In [ ]:
import numpy as np 
from numpy.linalg import norm

In [ ]:
vector_row = np.array([[1, -5, 3, 2, 4]])
print(vector_row)
new_vector = vector_row.T
print(new_vector)

norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)

print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)

### Vector Operations 

You would be familiar with vector operations. Let's see some examples in code here. 

In [ ]:
u = np.array([[0, 3, 2]])
v = np.array([[4, 1, 1]])
w = np.array([[0, -2, 0]])

x = 3*u - 2*v + 4*w

print(x)

In [ ]:
print(u)
print(v)
print(v.T)

u.dot(v)   #  .... Read the error! 

In [ ]:
print(u.shape)
print(v.shape)

In [ ]:
u = np.array([[0, 3, 2]])
v = np.array([4, 1, 1])    # notice the change here! 

x = u * v 

print(x)

In [ ]:
print(u)
print(v)
print(v.T) # Does nothing ... 

u.dot(v)   # this works here! 

In [ ]:
print(u.shape)
print(v.shape)

## Matrices 

Let's see the basics of matrices one more time. Let's also see the relevant terminlogy side by side. 

### Matrix Multiplication 

In [ ]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))

np.dot(Q, P) # can't do that

### Determinants 

In [ ]:
from numpy.linalg import det

M = np.array(
             [  [0,2,1,3], 
                [3,2,8,1], 
                [1,0,0,3],
                [0,3,2,1]  ]
            )
print('M:\n', M)

print('Determinant: %.1f' % det(M))

I = np.eye(4)  # eye-dentity matrix 

print('I:\n', I)
print('M*I:\n', np.dot(M, I))

Highly recomment the video by 3Blue1Brown on determinants: https://www.youtube.com/watch?v=Ip3X9LOh2dk 

### Inverse, Singular, Ill-conditioned

When you multiply something by a matrix and you want to get back, you multiply the result with the inverse of the original matrix. This is similar to multiplying by the reciprocal to reverse the effect of a multiplication. 

In [ ]:
from numpy.linalg import inv

print('Inv M:\n', inv(M))

In [ ]:
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])     # P has no inverse since it is singular. 

print('det(P):', det(P))

inv(P)

So, multiplying by a singular matrix is sort of like multiplying by 0. It's not reversible. 

*Ill-conditioned* matrices are not singular but their determinant is very close to 0. This makes them problematic just like multiplication by very small numbers can lead to overflow, underflow etc. 

### Rank, Full Rank, Condition Number, Augmented Matrix 

Rank, $rank(A)$, is the number of linearly independent columns or rows of $A$. 

Full rank if $rank(A) = min(m, n)$ for an $m \times n$ matrix. 

Condition Number: How close is a matrix to being ill-conditioned. Higher is closer to being singular. 

Augmented matrix: $[A | y]$ where $A$ is a matrix and $y$ is a vector. $y$ is called *new* if it cannot be expressed as a combination of columns of $A$. In this case, $rank([A|y]) = rank(A) + 1$ (because we just added a new independent column!) 

In [ ]:
from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))

print('Rank:\n', matrix_rank(A))

y = np.array([[1, 2, 1]]).T    # need a column vector. Easier to create it using .T 

A_y = np.concatenate((A, y), axis = 1)  # Notice the axis 
print('Augmented matrix:\n', A_y)

# Solving Linear Equations 

## LU Decomposition 

In [3]:
import numpy as np 
from numpy.linalg import inv

import scipy 
from scipy.linalg import lu 

In [4]:
help(lu)

Help on function lu in module scipy.linalg.decomp_lu:

lu(a, permute_l=False, overwrite_a=False, check_finite=True)
    Compute pivoted LU decomposition of a matrix.
    
    The decomposition is::
    
        A = P L U
    
    where P is a permutation matrix, L lower triangular with unit
    diagonal elements, and U upper triangular.
    
    Parameters
    ----------
    a : (M, N) array_like
        Array to decompose
    permute_l : bool, optional
        Perform the multiplication P*L (Default: do not permute)
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    
    Returns
    -------
    **(If permute_l == False)**
    
    p : (M, M) ndarray
        Permutation matri

In [30]:
A = np.array([ 
              [  1,  1,   1,   1 ], 
              [  2,  3,   1,   5 ], 
              [ -1,  1,  -5,   3 ], 
              [  3,  1,   7,  -2 ]  
             ], dtype=float)

In [5]:
P, L, U = lu(A)

print("A:")
print(A)

print("P:")   # What is this guy? 
print(P)

print("L:")
print(L)

print("U:")
print(U)

# Is the answer the same as what we got? 

A:
[[ 1.  1.  1.  1.]
 [ 2.  3.  1.  5.]
 [-1.  1. -5.  3.]
 [ 3.  1.  7. -2.]]
P:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L:
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  0.57142857  1.          0.        ]
 [ 0.33333333  0.28571429  0.5         1.        ]]
U:
[[ 3.          1.          7.         -2.        ]
 [ 0.          2.33333333 -3.66666667  6.33333333]
 [ 0.          0.         -0.57142857 -1.28571429]
 [ 0.          0.          0.          0.5       ]]


In [6]:
L = P.dot(L)   # Let's just do this once 

In [7]:
L.dot(U)     # Produces the same result though 

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  1.,  5.],
       [-1.,  1., -5.,  3.],
       [ 3.,  1.,  7., -2.]])

In [34]:
A

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  1.,  5.],
       [-1.,  1., -5.,  3.],
       [ 3.,  1.,  7., -2.]])

In [35]:
L.dot(U) == A   # !!! the horror! 

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
np.allclose(L.dot(U), A)  # Why? 

True

In [15]:
y = np.array([10, 31, -2, 18])       # Is something wrong here? 
print(y)

[[10]
 [31]
 [-2]
 [18]]


$ Lm = y$

Let's move L to the other side of the equation. 

$ L^{-1}Lm = L^{-1}y$

And cancel out ... 

$ m = L^{-1}y$

In [16]:
m = inv(L).dot(y)  

In [17]:
print(m)

[[18.        ]
 [19.        ]
 [-6.85714286]
 [ 2.        ]]


In [18]:
x = inv(U).dot(m)

In [19]:
print(x)   # Match this with our on-paper results. 

[[1.]
 [2.]
 [3.]
 [4.]]


In [25]:
yp = A.dot(x)
print(yp)

[[10.]
 [31.]
 [-2.]
 [18.]]


In [26]:
np.allclose(y, yp)

True

## Gauss-Seidel Method

$
\begin{eqnarray*}
8x_1 + 3x_2 - 3x_3 &=& 14 \\
-2x_1 - 8x_2 + 5x_3 &=& 5 \\
3x_1 + 5x_2 + 10x_3 & =& -8 \\
\end{eqnarray*}
$

In [77]:
a = [
        [ 8,  3, -3 ], 
        [-2, -8,  5 ], 
        [ 3,  5,  10]
    ]

# Find diagonal coefficients
diag = np.diag(np.abs(a)) 
print(diag)

[ 8  8 10]


In [78]:
np.sum(np.abs(a), axis=1)

array([14, 15, 18])

In [79]:
# Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag 
print(off_diag)

[6 7 8]


In [122]:
if np.all(diag > off_diag):
    print('matrix is diagonally dominant')    # will converge (sufficient condition)
else:
    print('NOT diagonally dominant')          # may or may not converge (because NOT a necessary condition)

NOT diagonally dominant


Re-arrange the original: 

$
\begin{eqnarray*}
8x_1 + 3x_2 - 3x_3 &=& 14 \\
-2x_1 - 8x_2 + 5x_3 &=& 5 \\
3x_1 + 5x_2 + 10x_3 & =& -8 \\
\end{eqnarray*}
$

as: 

$
\begin{eqnarray*}
x_1 &=& (14 - 3x_2 + 3x_3)  / 8\\
x_2 &=& (5  + 2x_1 - 5x_3) / (-8) \\ 
x_3 &=& (-8 - 3x_1 - 5x_2) / 10
\end{eqnarray*}
$

In [107]:
# Let's apply the iterative method starting at 0 

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.001   # also try better precision
converged = False

x_old = np.array([x1, x2, x3])

In [108]:
max_iterations = 50

In [109]:
print('Iteration results')
print('k      x1        x2        x3 ')

for k in range(1, max_iterations):
    
    x1 = (14 -  3*x2  +  3*x3)  /  8
    x2 = (5  +  2*x1  -  5*x3)  / (-8)
    x3 = (-8 -  3*x1  -  5*x2)  / 10
    
    x = np.array([x1, x2, x3])
    
    print("%2d   %.4f   %.4f   %.4f" % (k, x1, x2, x3))
    
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converged, increase the # of iterations')

Iteration results
k      x1        x2        x3 
 1   1.7500   -1.0625   -0.7937
 2   1.8508   -1.5838   -0.5633
 3   2.1327   -1.5103   -0.6847
 4   2.0596   -1.5678   -0.6340
 5   2.1002   -1.5463   -0.6569
 6   2.0835   -1.5565   -0.6468
 7   2.0911   -1.5520   -0.6513
 8   2.0878   -1.5540   -0.6493
 9   2.0893   -1.5531   -0.6502
10   2.0886   -1.5535   -0.6498
Converged!


In [110]:
8*x1 + 3*x2 - 3*x3

13.997673687371334

In [111]:
-2*x1 - 8*x2 + 5*x3

5.001948405718945

In [112]:
3*x1 + 5*x2 + 10*x3 

-8.0

Let's try one where this does NOT work!

In [123]:
a = [
        [ 1,  3, -3 ], 
        [-2, -1,  5 ], 
        [ 3,  5,  1]
    ]

# Find diagonal coefficients
diag = np.diag(np.abs(a)) 
print(diag)

off_diag = np.sum(np.abs(a), axis=1) - diag 
print(off_diag)

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')    
else:
    print('NOT diagonally dominant') 

[1 1 1]
[6 7 8]
NOT diagonally dominant


In [126]:
# Let's apply the iterative method starting at 0 

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.001   # also try better precision
max_iterations = 10
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print('k      x1        x2        x3 ')

for k in range(1, max_iterations):
    
    x1 = (14 -  3*x2  +  3*x3)  /  1
    x2 = (5  +  2*x1  -  5*x3)  / (-1)
    x3 = (-8 -  3*x1  -  5*x2)  / 1
    
    x = np.array([x1, x2, x3])
    
    print("%2d   %.4f   %.4f   %.4f" % (k, x1, x2, x3))
    
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converged, increase the # of iterations')
    
# It may still have converged but it didn't ... 

Iteration results
k      x1        x2        x3 
 1   14.0000   -33.0000   115.0000
 2   458.0000   -346.0000   348.0000
 3   2096.0000   -2457.0000   5989.0000
 4   25352.0000   -20764.0000   27756.0000
 5   145574.0000   -152373.0000   325135.0000
 6   1432538.0000   -1239406.0000   1899408.0000
 7   9416456.0000   -9335877.0000   18430009.0000
 8   83297672.0000   -74445304.0000   122333496.0000
 9   590336414.0000   -569005353.0000   1074017515.0000
Not converge, increase the # of iterations
